# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-16 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20200416_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='address',
            field=models.CharField(default='广东省茂名市', max_length=128),
        ),
    ]
